--
-- DDL for the Spring Batch Soccer Points Application (Optimized for H2)
--
-- This script uses H2-specific auto-increment syntax (IDENTITY)
--

-- -------------------------------------------------------------------------
-- 1. TEAM Table (Replaces CLUB) - Stores both clubs and national teams.
-- -------------------------------------------------------------------------

CREATE TABLE TEAM (
                      TEAM_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                      NAME VARCHAR(255) NOT NULL,
                      TEAM_TYPE VARCHAR(20) NOT NULL, -- 'CLUB' or 'NATIONAL'

    -- Club Specific Details (can be NULL for National Teams)
                      STADIUM_NAME VARCHAR(255),
                      ESTABLISHED_YEAR INT,
                      NICKNAME VARCHAR(255),
                      STADIUM_CAPACITY INT,

                      COUNTRY_CODE VARCHAR(3) NOT NULL, -- e.g., 'ENG', 'BRA' (Essential for all)

    -- Audit Columns
                      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      UPDATED_BY VARCHAR(100) NOT NULL,

                      UNIQUE (NAME)
);


-- -------------------------------------------------------------------------
-- 2. COMPETITION Table
-- -------------------------------------------------------------------------

CREATE TABLE COMPETITION (
                             COMPETITION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                             NAME VARCHAR(255) NOT NULL,
                             COUNTRY_ID INT NOT NULL, -- Numeric ID reference, '999' for international/continental

    -- Audit Columns
                             CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             UPDATED_BY VARCHAR(100) NOT NULL,

                             UNIQUE (NAME)
);


-- -------------------------------------------------------------------------
-- 3. TEAM_COMPETITION_SEASON Table (Replaces CLUB_COMPETITION_SEASON)
-- -------------------------------------------------------------------------

CREATE TABLE TEAM_COMPETITION_SEASON (
                                         TEAM_COMPETITION_SEASON_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                                         TEAM_ID BIGINT NOT NULL,
                                         COMPETITION_ID BIGINT NOT NULL,

                                         SEASON_START_YEAR INT NOT NULL,
                                         SEASON_END_YEAR INT,

    -- Audit Columns
                                         CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                         UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                         UPDATED_BY VARCHAR(100) NOT NULL,

    -- Foreign Key Constraints
                                         FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID),
                                         FOREIGN KEY (COMPETITION_ID) REFERENCES COMPETITION(COMPETITION_ID),

                                         UNIQUE (TEAM_ID, COMPETITION_ID, SEASON_START_YEAR)
);


-- -------------------------------------------------------------------------
-- 4. PLAYER Table - Stores fantasy users and their total score.
-- Security and Audit details included.
-- -------------------------------------------------------------------------

CREATE TABLE PLAYER (
                        PLAYER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                        USER_NAME VARCHAR(100) NOT NULL,
                        EMAIL VARCHAR(255) NOT NULL,
                        TOTAL_POINTS INT DEFAULT 0 NOT NULL,  -- Cumulative points across all weeks/rounds

    -- Security Fields
                        PASSWORD_HASH VARCHAR(255) NOT NULL, -- Stores the encrypted (hashed) password
                        PASSWORD_EXPIRY_DATE TIMESTAMP,     -- Date when the password must be reset
                        LAST_LOGIN_DATE TIMESTAMP,          -- Date of the player's last successful login

    -- Audit Columns
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        UPDATED_BY VARCHAR(100) NOT NULL,

                        UNIQUE (USER_NAME),
                        UNIQUE (EMAIL)
);


-- -------------------------------------------------------------------------
-- 5. GAME Table - Stores weekly fixtures and actual results.
-- -------------------------------------------------------------------------

CREATE TABLE GAME (
                      GAME_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                      COMPETITION_ID BIGINT NOT NULL,
                      SEASON_START_YEAR INT NOT NULL,

                      GAME_WEEK INT NOT NULL, -- Can be treated as 'Round Number' or 'Stage ID' for tournaments
                      GAME_DATE DATE NOT NULL,

                      HOME_TEAM_ID BIGINT NOT NULL,
                      AWAY_TEAM_ID BIGINT NOT NULL,

    -- Actual Results (Set once game is finished)
                      HOME_SCORE INT,
                      AWAY_SCORE INT,

    -- Statuses to handle batch processing logic
                      STATUS VARCHAR(50) NOT NULL, -- e.g., 'SCHEDULED', 'FINISHED', 'POSTPONED'
                      POINTS_UPDATED_FLAG BOOLEAN DEFAULT FALSE NOT NULL, -- Crucial for Batch job

    -- Audit Columns
                      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      UPDATED_BY VARCHAR(100) NOT NULL,

    -- Foreign Key Constraints
                      FOREIGN KEY (COMPETITION_ID) REFERENCES COMPETITION(COMPETITION_ID),
                      FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAM(TEAM_ID),
                      FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAM(TEAM_ID),

    -- Constraint to prevent a club playing itself (optional but good practice)
                      CHECK (HOME_TEAM_ID <> AWAY_TEAM_ID)
);


-- -------------------------------------------------------------------------
-- 6. SELECTION Table - Stores player predictions for each game.
-- -------------------------------------------------------------------------

CREATE TABLE SELECTION (
                           SELECTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                           PLAYER_ID BIGINT NOT NULL,
                           GAME_ID BIGINT NOT NULL,

    -- Player's Prediction
                           PREDICTED_HOME_SCORE INT NOT NULL,
                           PREDICTED_AWAY_SCORE INT NOT NULL,

    -- Batch Job Results
                           POINTS_AWARDED INT DEFAULT 0 NOT NULL,
                           SELECTION_PROCESSED_FLAG BOOLEAN DEFAULT FALSE NOT NULL,

    -- Audit Columns
                           CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           UPDATED_BY VARCHAR(100) NOT NULL,

    -- Foreign Key Constraints
                           FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
                           FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID),

    -- Unique Constraint: A player can only pick a game once.
                           UNIQUE (PLAYER_ID, GAME_ID)
);


-- -------------------------------------------------------------------------
-- 7. PLAYER_WEEKLY_SCORE Table - Stores player points per week/round/stage.
-- -------------------------------------------------------------------------

CREATE TABLE PLAYER_WEEKLY_SCORE (
                                     PLAYER_WEEKLY_SCORE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,

                                     PLAYER_ID BIGINT NOT NULL,
                                     COMPETITION_ID BIGINT NOT NULL,
                                     SEASON_START_YEAR INT NOT NULL,
                                     GAME_WEEK INT NOT NULL, -- The specific period identifier (Week, Round, Stage)

                                     WEEKLY_POINTS INT DEFAULT 0 NOT NULL,

    -- Audit Columns
                                     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                     UPDATED_BY VARCHAR(100) NOT NULL,

    -- Foreign Key Constraints
                                     FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
                                     FOREIGN KEY (COMPETITION_ID) REFERENCES COMPETITION(COMPETITION_ID),

    -- Unique constraint: A player can only have one score record per week/round/competition
                                     UNIQUE (PLAYER_ID, COMPETITION_ID, SEASON_START_YEAR, GAME_WEEK)
);

CREATE TABLE DATA_VERSION (
    -- Unique identifier for the loaded dataset (e.g., '1.0.0')
                              VERSION VARCHAR(100) NOT NULL PRIMARY KEY,
    -- Timestamp when the version was successfully loaded/recorded
                              LOAD_DATE TIMESTAMP NOT NULL
);